version: '{build}'
image: WMF 5

environment:
  mail_user: majkinetor@gmail.com

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: ./setup.ps1

build_script:
- ps: |
    $version = ./build.ps1
    Update-AppveyorBuild -Version $version

test_script:
- ps: |
    $testResultsFile = ".\TestsResults.xml"
    $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

    "Uploading test results"
    $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
    (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $testResultsFile))
    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed." }

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: _build\*\*.nupkg
- path: _build\*\*.7z

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

